### ISSUE TITLE
wx:getUserinfo已经慢慢不能用了呀，还能上线吗

### ISSUE THREAD

**Issue by jljaoe** [guren-cloud/vpush-pro-sdk#2]
如题，已经用了好久了，但是就怕那天不能用了，请赐教，或者修复

**Comment by safe-dog** [comment]
可以的，这个默认如果没授权，无法获取，已经授权过了的，会自动获取。
并不影响功能的使用的（只是用户列表展示不出用户的性别昵称头像等信息而已，不影响推送等功能）
