### ISSUE TITLE
我这里addFormId 有点小问题能帮我看下么

### ISSUE THREAD

**Issue by LSKReno** [guren-cloud/vpush-pro-sdk#3]
![1_WVRUW`HSSP4`KIL4XSC(A](https://user-images.githubusercontent.com/34096350/57664895-711ee700-762c-11e9-85c8-0cc27a6e17b9.png)

**Comment by safe-dog** [comment]
这是你没有在app.js中引入并初始化vPush的原因，导致无法获取到vPush.addFormId这个函数
